/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerDto } from '../../models/player-dto';

export interface AddPlayersFromGoogleSheet$Params {
}

export function addPlayersFromGoogleSheet(http: HttpClient, rootUrl: string, params?: AddPlayersFromGoogleSheet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlayerDto>>> {
  const rb = new RequestBuilder(rootUrl, addPlayersFromGoogleSheet.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlayerDto>>;
    })
  );
}

addPlayersFromGoogleSheet.PATH = '/api/players/update';
