/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerDto } from '../../models/player-dto';

export interface GetPlayer$Params {
  id: number;
}

export function getPlayer(http: HttpClient, rootUrl: string, params: GetPlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<PlayerDto>> {
  const rb = new RequestBuilder(rootUrl, getPlayer.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlayerDto>;
    })
  );
}

getPlayer.PATH = '/api/players/{id}';
