/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerEventsDto } from '../../models/player-events-dto';

export interface GetPlayerEvents$Params {
  id: number;
}

export function getPlayerEvents(http: HttpClient, rootUrl: string, params: GetPlayerEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlayerEventsDto>>> {
  const rb = new RequestBuilder(rootUrl, getPlayerEvents.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlayerEventsDto>>;
    })
  );
}

getPlayerEvents.PATH = '/api/players/events/{id}';
