/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StandingDto } from '../../models/standing-dto';

export interface GetStandings$Params {
  division: string;
  year: number;
}

export function getStandings(http: HttpClient, rootUrl: string, params: GetStandings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StandingDto>>> {
  const rb = new RequestBuilder(rootUrl, getStandings.PATH, 'get');
  if (params) {
    rb.path('division', params.division, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StandingDto>>;
    })
  );
}

getStandings.PATH = '/api/standings/{year}/{division}';
