/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CustomUser } from './models/custom-user';
export type { EventDto } from './models/event-dto';
export type { EventPointsDto } from './models/event-points-dto';
export type { PlayerDto } from './models/player-dto';
export type { PlayerEventsDto } from './models/player-events-dto';
export type { RoundDtOsmall } from './models/round-dt-osmall';
export type { StandingDto } from './models/standing-dto';
export type { TournamentDto } from './models/tournament-dto';
