/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TournamentResourceService } from './services/tournament-resource.service';
export { PlayersService } from './services/players.service';
export { EventResourceService } from './services/event-resource.service';
export { LoginControllerService } from './services/login-controller.service';
export { CreateNewUserControllerService } from './services/create-new-user-controller.service';
export { StandingsResourceService } from './services/standings-resource.service';
export { HomeResourceService } from './services/home-resource.service';
