/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TournamentResourceService } from './services/tournament-resource.service';
export { PlayersService } from './services/players.service';
export { EventsService } from './services/events.service';
export { LogInService } from './services/log-in.service';
export { CreateUserService } from './services/create-user.service';
export { StandingsService } from './services/standings.service';
export { HomeResourceService } from './services/home-resource.service';
