/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentDto } from '../../models/tournament-dto';

export interface GetAllTournaments$Params {
}

export function getAllTournaments(http: HttpClient, rootUrl: string, params?: GetAllTournaments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TournamentDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllTournaments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TournamentDto>>;
    })
  );
}

getAllTournaments.PATH = '/api/tournaments';
