/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentDto } from '../../models/tournament-dto';

export interface GetTournament$Params {
  id: number;
}

export function getTournament(http: HttpClient, rootUrl: string, params: GetTournament$Params, context?: HttpContext): Observable<StrictHttpResponse<TournamentDto>> {
  const rb = new RequestBuilder(rootUrl, getTournament.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentDto>;
    })
  );
}

getTournament.PATH = '/api/tournaments/{id}';
