/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventPointsDto {
  championship?: boolean;
  eventId?: number;
  eventPoints?: number;
  included?: boolean;
  points?: number;
}
