/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlayerDto {
  firstname?: string;
  id?: number;
  isPro?: boolean;
  lastname?: string;
  pdgaNumber?: number;
  sdaNumber?: number;
  swisstourLicense: boolean;
}
