/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoundDtOsmall } from '../models/round-dt-osmall';
export interface PlayerEventsDto {
  city?: string;
  country?: string;
  displayName?: string;
  division?: string;
  endDate?: string;
  eventId?: number;
  hasResults?: boolean;
  id?: number;
  infoLink?: string;
  isChampionship?: boolean;
  isSwisstour?: boolean;
  name?: string;
  numberPlayers?: number;
  points?: number;
  purse?: number;
  registrationLink?: string;
  registrationStart?: string;
  rounds?: Array<RoundDtOsmall>;
  startDate?: string;
  swisstourType?: string;
  tier?: string;
  tournamentPlace?: number;
  tournamentPoints?: number;
  tournamentPrize?: number;
  tournamentRating?: number;
  tournamentScore?: number;
  year?: number;
}
