/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventPointsDto } from '../models/event-points-dto';
export interface StandingDto {
  eventPoints?: Array<EventPointsDto>;
  playerId?: number;
  rank?: number;
  totalPoints?: number;
}
