/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TournamentDto {
  division: string;
  event: number;
  id?: number;
  place: number;
  player: number;
  points?: number;
  prize?: number;
  rating?: number;
  score?: number;
}
