/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEvent } from '../fn/events/create-event';
import { CreateEvent$Params } from '../fn/events/create-event';
import { deleteEvent } from '../fn/events/delete-event';
import { DeleteEvent$Params } from '../fn/events/delete-event';
import { EventDto } from '../models/event-dto';
import { getEvent } from '../fn/events/get-event';
import { GetEvent$Params } from '../fn/events/get-event';
import { getEventResults } from '../fn/events/get-event-results';
import { GetEventResults$Params } from '../fn/events/get-event-results';
import { getEvents } from '../fn/events/get-events';
import { GetEvents$Params } from '../fn/events/get-events';
import { getEventsByYear } from '../fn/events/get-events-by-year';
import { GetEventsByYear$Params } from '../fn/events/get-events-by-year';
import { updateEvent } from '../fn/events/update-event';
import { UpdateEvent$Params } from '../fn/events/update-event';

@Injectable({ providedIn: 'root' })
export class EventsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getEvent()` */
  static readonly GetEventPath = '/api/events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEvent$Response(params: GetEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<EventDto>> {
    const obs = getEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEvent(params: GetEvent$Params, context?: HttpContext): Observable<EventDto> {
    const resp = this.getEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventDto>): EventDto => r.body)
    );
  }

  /** Path part for operation `updateEvent()` */
  static readonly UpdateEventPath = '/api/events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEvent$Response(params: UpdateEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<EventDto>> {
    const obs = updateEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEvent(params: UpdateEvent$Params, context?: HttpContext): Observable<EventDto> {
    const resp = this.updateEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventDto>): EventDto => r.body)
    );
  }

  /** Path part for operation `deleteEvent()` */
  static readonly DeleteEventPath = '/api/events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEvent$Response(params: DeleteEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEvent(params: DeleteEvent$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getEvents()` */
  static readonly GetEventsPath = '/api/events';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEvents$Response(params?: GetEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventDto>>> {
    const obs = getEvents(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEvents(params?: GetEvents$Params, context?: HttpContext): Observable<Array<EventDto>> {
    const resp = this.getEvents$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<EventDto>>): Array<EventDto> => r.body)
    );
  }

  /** Path part for operation `createEvent()` */
  static readonly CreateEventPath = '/api/events';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEvent$Response(params: CreateEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<EventDto>> {
    const obs = createEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEvent(params: CreateEvent$Params, context?: HttpContext): Observable<EventDto> {
    const resp = this.createEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EventDto>): EventDto => r.body)
    );
  }

  /** Path part for operation `getEventResults()` */
  static readonly GetEventResultsPath = '/api/events/results/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEventResults()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEventResults$Response(params: GetEventResults$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = getEventResults(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEventResults$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEventResults(params: GetEventResults$Params, context?: HttpContext): Observable<number> {
    const resp = this.getEventResults$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getEventsByYear()` */
  static readonly GetEventsByYearPath = '/api/events/year/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEventsByYear()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEventsByYear$Response(params: GetEventsByYear$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventDto>>> {
    const obs = getEventsByYear(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEventsByYear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEventsByYear(params: GetEventsByYear$Params, context?: HttpContext): Observable<Array<EventDto>> {
    const resp = this.getEventsByYear$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<EventDto>>): Array<EventDto> => r.body)
    );
  }

}
