/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPlayer } from '../fn/players/create-player';
import { CreatePlayer$Params } from '../fn/players/create-player';
import { deletePlayer } from '../fn/players/delete-player';
import { DeletePlayer$Params } from '../fn/players/delete-player';
import { getAllPlayers } from '../fn/players/get-all-players';
import { GetAllPlayers$Params } from '../fn/players/get-all-players';
import { getPlayer } from '../fn/players/get-player';
import { GetPlayer$Params } from '../fn/players/get-player';
import { getPlayerEvents } from '../fn/players/get-player-events';
import { GetPlayerEvents$Params } from '../fn/players/get-player-events';
import { PlayerDto } from '../models/player-dto';
import { PlayerEventsDto } from '../models/player-events-dto';
import { updatePlayer } from '../fn/players/update-player';
import { UpdatePlayer$Params } from '../fn/players/update-player';

@Injectable({ providedIn: 'root' })
export class PlayersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPlayer()` */
  static readonly GetPlayerPath = '/api/players/{id}';

  /**
   * Get player by id
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPlayer()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayer$Response(params: GetPlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<PlayerDto>> {
    const obs = getPlayer(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get player by id
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPlayer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayer(params: GetPlayer$Params, context?: HttpContext): Observable<PlayerDto> {
    const resp = this.getPlayer$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PlayerDto>): PlayerDto => r.body)
    );
  }

  /** Path part for operation `updatePlayer()` */
  static readonly UpdatePlayerPath = '/api/players/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePlayer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePlayer$Response(params: UpdatePlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = updatePlayer(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePlayer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePlayer(params: UpdatePlayer$Params, context?: HttpContext): Observable<number> {
    const resp = this.updatePlayer$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deletePlayer()` */
  static readonly DeletePlayerPath = '/api/players/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePlayer()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePlayer$Response(params: DeletePlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deletePlayer(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePlayer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePlayer(params: DeletePlayer$Params, context?: HttpContext): Observable<void> {
    const resp = this.deletePlayer$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllPlayers()` */
  static readonly GetAllPlayersPath = '/api/players';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPlayers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlayers$Response(params?: GetAllPlayers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlayerDto>>> {
    const obs = getAllPlayers(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPlayers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlayers(params?: GetAllPlayers$Params, context?: HttpContext): Observable<Array<PlayerDto>> {
    const resp = this.getAllPlayers$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PlayerDto>>): Array<PlayerDto> => r.body)
    );
  }

  /** Path part for operation `createPlayer()` */
  static readonly CreatePlayerPath = '/api/players';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPlayer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPlayer$Response(params: CreatePlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = createPlayer(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPlayer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPlayer(params: CreatePlayer$Params, context?: HttpContext): Observable<number> {
    const resp = this.createPlayer$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getPlayerEvents()` */
  static readonly GetPlayerEventsPath = '/api/players/events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPlayerEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerEvents$Response(params: GetPlayerEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlayerEventsDto>>> {
    const obs = getPlayerEvents(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPlayerEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerEvents(params: GetPlayerEvents$Params, context?: HttpContext): Observable<Array<PlayerEventsDto>> {
    const resp = this.getPlayerEvents$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PlayerEventsDto>>): Array<PlayerEventsDto> => r.body)
    );
  }

}
