/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTournament } from '../fn/tournament-resource/create-tournament';
import { CreateTournament$Params } from '../fn/tournament-resource/create-tournament';
import { deleteTournament } from '../fn/tournament-resource/delete-tournament';
import { DeleteTournament$Params } from '../fn/tournament-resource/delete-tournament';
import { getAllTournaments } from '../fn/tournament-resource/get-all-tournaments';
import { GetAllTournaments$Params } from '../fn/tournament-resource/get-all-tournaments';
import { getTournament } from '../fn/tournament-resource/get-tournament';
import { GetTournament$Params } from '../fn/tournament-resource/get-tournament';
import { TournamentDto } from '../models/tournament-dto';
import { updateTournament } from '../fn/tournament-resource/update-tournament';
import { UpdateTournament$Params } from '../fn/tournament-resource/update-tournament';

@Injectable({ providedIn: 'root' })
export class TournamentResourceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTournament()` */
  static readonly GetTournamentPath = '/api/tournaments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTournament()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTournament$Response(params: GetTournament$Params, context?: HttpContext): Observable<StrictHttpResponse<TournamentDto>> {
    const obs = getTournament(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTournament$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTournament(params: GetTournament$Params, context?: HttpContext): Observable<TournamentDto> {
    const resp = this.getTournament$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentDto>): TournamentDto => r.body)
    );
  }

  /** Path part for operation `updateTournament()` */
  static readonly UpdateTournamentPath = '/api/tournaments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTournament()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTournament$Response(params: UpdateTournament$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = updateTournament(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTournament$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTournament(params: UpdateTournament$Params, context?: HttpContext): Observable<number> {
    const resp = this.updateTournament$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deleteTournament()` */
  static readonly DeleteTournamentPath = '/api/tournaments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTournament()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTournament$Response(params: DeleteTournament$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteTournament(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTournament$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTournament(params: DeleteTournament$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteTournament$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllTournaments()` */
  static readonly GetAllTournamentsPath = '/api/tournaments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTournaments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTournaments$Response(params?: GetAllTournaments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TournamentDto>>> {
    const obs = getAllTournaments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTournaments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTournaments(params?: GetAllTournaments$Params, context?: HttpContext): Observable<Array<TournamentDto>> {
    const resp = this.getAllTournaments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<TournamentDto>>): Array<TournamentDto> => r.body)
    );
  }

  /** Path part for operation `createTournament()` */
  static readonly CreateTournamentPath = '/api/tournaments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTournament()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTournament$Response(params: CreateTournament$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = createTournament(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTournament$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTournament(params: CreateTournament$Params, context?: HttpContext): Observable<number> {
    const resp = this.createTournament$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
